name: X-Account Auto KeepAlive

on:
  schedule:
    - cron: '30 2,8,14,20 * * *'
  workflow_dispatch: {}

jobs:
  run-x-account:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      secrets: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Requests
        run: pip install requests

      - name: Run Script for Account X
        id: run_script
        env:
          GITHUB_REPO_NAME: ${{ github.repository }}
          CLIENT_ID: ${{ secrets.OD_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.OD_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.OD_REFRESH_TOKEN }}
          TENANT_ID: ${{ secrets.OD_TENANT_ID }}
        run: python main.py

      - name: Update Secret
        if: steps.run_script.outputs.NEW_REFRESH_TOKEN != ''
        uses: hman75/github-set-secret@v2.0.0
        with:
          name: 'OD_REFRESH_TOKEN'
          value: ${{ steps.run_script.outputs.NEW_REFRESH_TOKEN }}
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
