name: Z-Account Auto KeepAlive
on:
  schedule:
    - cron: '0 */6 * * *'   # UTC 每6小时
  workflow_dispatch: {}
jobs:
  run-z-account:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: pip install requests pynacl
      - name: Random Delay
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo ">>> Manual Trigger: Skipping delay."
          else
            WAIT_SEC=$((RANDOM % 3600))
            echo "错峰执行，随机等待 ${WAIT_SEC} 秒..."
            sleep $WAIT_SEC
          fi
      - name: Run Script for Account Z
        env:
          GITHUB_REPO_NAME: ${{ github.repository }}
          CLIENT_ID: ${{ secrets.Z_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.Z_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.Z_REFRESH_TOKEN }}
          TENANT_ID: ${{ secrets.Z_TENANT_ID }}
          GH_PAT: ${{ secrets.AUTH_PAT }}
          SECRET_NAME: Z_REFRESH_TOKEN
        run: python main.py
